swagger: '2.0'
info:
  title: My API
  version: 1.0.0
  description: My API description
host: localhost:3001
basePath: /
schemes:
  - http
paths:
  /hello:
    get:
      description: Returns a hello world messagessssss
      parameters:
        description: limit the data
      responses:
        '200':
          description: OK
          schema:
            type: string
/users:
  post:
    summary: Create a new user
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    responses:
      '201':
        description: Created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
